openapi: 3.0.3
info:
  version: 1.0.0
  title: Online Grocery Store Service - Online Grocery Store API
  description: API for online grocery store.
servers:
  - url: http://localhost:8080
    description: local server url
paths:
  /api/v1/online/grocery/orders:
    post:
      tags:
        - grocery-store-controller
      operationId: calculateOrder
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ItemDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ReceiptDTO'
  /api/v1/online/grocery/prices:
    get:
      tags:
        - grocery-store-controller
      operationId: getPrices
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ItemDTO'
  /api/v1/online/grocery/discounts:
    get:
      tags:
        - grocery-store-controller
      operationId: getDiscountRules
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
components:
  schemas:
    ItemDTO:
      type: object
      properties:
        itemType:
          type: string
          enum:
            - BREAD
            - VEGETABLE
            - BEER
        name:
          type: string
        unitPrice:
          type: number
          format: double
        quantity:
          type: integer
          format: int32
          minimum: 1
        details:
          type: string
      required:
        - itemType
        - quantity
    ReceiptDTO:
      type: object
      properties:
        total:
          type: number
          format: double
        breakdown:
          type: array
          items:
            type: string
